DELETE http://localhost:3001/api/blogs/69a1e23547eedbcebcbcaecb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwiaWQiOiI2OWExZDZlZmI4YzExYzg5ZDE4MGVjYjUiLCJpYXQiOjE3NzIyMTY4NjB9.XLR_IymWHZ3Z5RJNDr1CUHhquqEbfYhKQVh_LLaBks8